### ISSUE TITLE
Raydium Buy Error

### ISSUE THREAD

**Issue by CryptoX78** [kokiez/solana-sniper#16]
Hi, over the last few days, I’ve been getting this error when the program tries to execute a swap on Raydium. It seems to be happening every second or third swap. From the message, it looks like it’s having trouble finding the pool:

Response: WIF
[Discord Webhook] Discord Webhook sent
No thread with the name 2DjjzcJRSTZpgKtnMDTstFxZuwLNDyT6tRxb995kNzKF is running.
Response: WIF
[Discord Webhook] Discord Webhook sent
Response: WIF
Token Address: 2DjjzcJRSTZpgKtnMDTstFxZuwLNDyT6tRxb995kNzKF
Token Price USD: 0.000002080000000
[Discord Webhook] Discord Webhook sent
Response: WIF
3. Get Route for swap...
Quote Response [ERROR] - NOT ENOUGH LIQUIDITY:  No route found
[Discord Webhook] Discord Webhook sent
Total Execution time: 1.141336441040039 seconds
[Jupiter] Buy Failed
[Discord Webhook] Discord Webhook sent
---------------[Raydium] Buy Started---------------
[Discord Webhook] Discord Webhook sent
Response: WIF
Exception in thread 2DjjzcJRSTZpgKtnMDTstFxZuwLNDyT6tRxb995kNzKF:
Traceback (most recent call last):
  File "C:\Users\Administrator\solana-sniper\raydium\create_close_account.py", line 92, in fetch_pool_keys
    amm_info = extract_pool_info(all_pools, mint)
  File "C:\Users\Administrator\solana-sniper\raydium\create_close_account.py", line 82, in extract_pool_info
    raise Exception(f'{mint} pool not found!')
Exception: 2DjjzcJRSTZpgKtnMDTstFxZuwLNDyT6tRxb995kNzKF pool not found!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 748, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    yield
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 815, in read_chunked
    self._update_chunk_length()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 752, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 623, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 803, in read_chunked
    with self._error_catcher():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 460, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\solana-sniper\amm_selection.py", line 143, in select_amm2trade
    txB_R = raydium_buy(ctx, desired_token_address, payer, invest_amount_sol)
  File "C:\Users\Administrator\solana-sniper\raydium\buy_swap.py", line 24, in buy
    pool_keys = fetch_pool_keys(str(mint))
  File "C:\Users\Administrator\solana-sniper\raydium\create_close_account.py", line 95, in fetch_pool_keys
    pools = resp.json()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 923, in text
    if not self.content:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

**Comment by kokiez** [comment]
raise Exception(f'{mint} pool not found!')
Exception: 2DjjzcJRSTZpgKtnMDTstFxZuwLNDyT6tRxb995kNzKF pool not found!

it clearly says what the error is.
